---
- hosts: build_servers
  become: yes

  tasks:
    - name: Ensure Python3 and pip3 are installed
      apt:
        name: 
          - python3
          - python3-pip
          - python3-venv
        state: present
        update_cache: yes

    - name: Create a virtual environment in /opt/myenv
      command: python3 -m venv /opt/myenv
      args:
        creates: /opt/myenv/bin/activate

    - name: Install Python modules in the virtual environment
      pip:
        virtualenv: /opt/myenv
        name: 
          - usaddress
          - playwright
          - js2py
          - bs4
          - phonenumbers
          - tldextract
          - pyyaml
          - csvkit
          - pandas
          - numpy
