---

- hosts: all
  become: true
  tasks:

  - name: updates repository index (apt)
    tags: always
    apt:
      update_cache: yes
    changed_when: false

- hosts: all
  become: true
  roles:
    - base

- hosts: build_servers
  become: true
  roles:
    - build_servers

- hosts: workstations
  become: true
  roles:
    - workstations

