---

- hosts: all
  become: true
  pre_tasks:

  - name: updates repository index (apt)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_os_family == "Debian"

- hosts: all
  become: true
  roles:
    - base

- hosts: build_servers
  become: true
  roles:
    - build_servers
