---
# Tasks for Master Node
- name: Get K3s node token from Master
  shell: cat /var/lib/rancher/k3s/server/node-token
  register: k3s_token
  when: inventory_hostname == "Master"

- name: Set K3s Master IP
  set_fact:
    k3s_master_ip: "{{ ansible_host }}"
  when: inventory_hostname == "Master"

# Tasks for Worker Nodes
- name: Install K3s agent on Worker nodes
  shell: |
    curl -sfL https://get.k3s.io | K3S_URL=https://{{ hostvars['Master'].k3s_master_ip }}:6443 K3S_TOKEN={{ hostvars['Master'].k3s_token.stdout }} sh -
  when: inventory_hostname != "Master"
