- name: Install Required Python modules
  tags: python
  block:
    - name: Ensure Python3 and pip3 are installed
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv
        state: present
        update_cache: yes

    - name: Create a virtual environment in project
      command: python3 -m venv /home/sasha/projects/rankrent-fe/myenv
      args:
        creates: /home/sasha/projects/rankrent-fe/myenv

    - name: Install Python modules in the virtual environment
      pip:
        virtualenv: /home/sasha/projects/rankrent-fe/myenv
        name:
          - usaddress
          - playwright
          - js2py
          - bs4
          - phonenumbers
          - tldextract
          - pyyaml
          - csvkit
          - pandas
          - numpy
